package code

import org.scalatest.wordspec.AnyWordSpec
import org.scalatest.matchers.should.Matchers

class MainSpec extends AnyWordSpec with Matchers {
  "getdefaultGrid" should {
    "be a 5x5 grid of Sand" in {
      Main.getDefaultGrid().toString() shouldBe """|.....
        |.....
        |.....
        |.....
        |.....""".stripMargin
    }
  }

  "gridWithRover" should {
    "be a 5x5 grid of Sand with a Rover pointing North at grid ref 0,0" in {
      Main.gridWithRover(Main.getDefaultGrid(), Main.defaultRover) shouldBe """|^....
        |.....
        |.....
        |.....
        |.....""".stripMargin
    }
  }
}
